### ISSUE TITLE
Canary branch is empy

### ISSUE THREAD

**Issue by Ramblurr** [components/ember-data#31]
The canary branch is empty. What happened to the canary builds?

**Comment by rwjblue** [comment]
Looks like when https://github.com/emberjs/data/pull/3907 was merged, the `dist/` that is published here was an empty directory.  

I'm sure @fivetanley is working on fixing, in the meantime you can lock to a prior SHA.

**Comment by fivetanley** [comment]
fixed in emberjs/data#3927
