### ISSUE TITLE
Latest beta and canary distributions don't contain ember-data.js.map

### ISSUE THREAD

**Issue by marcoow** [components/ember-data#32]
We're using the following ember-try configs for the [simplabs/ember-simple-auth](https://github.com/simplabs/ember-simple-auth) tests:

```js
{
  name: 'ember-beta',
  dependencies: {
    'ember': 'components/ember#beta',
    'ember-data': 'components/ember-data#beta'
  },
  resolutions: {
    'ember': 'beta',
    'ember-data': 'beta'
  }
},
{
  name: 'ember-canary',
  dependencies: {
    'ember': 'components/ember#canary',
    'ember-data': 'components/ember-data#canary'
  },
  resolutions: {
    'ember': 'canary',
    'ember-data': 'canary'
  }
}
```

The latest beta and canary branches don't contain the `ember-data.js.map` file though, causing Ember CLI to fail with:

```
ENOENT, no such file or directory '/home/travis/build/simplabs/ember-simple-auth/tmp/funnel-input_base_path-r4FlWJx6.tmp/0/bower_components/ember-data/ember-data.js.map'
```

See the travis build for reference: https://travis-ci.org/simplabs/ember-simple-auth/builds/91904720

**Comment by offirgolan** [comment]
Bump. Having the same issue on my end as well.

**Comment by rwjblue** [comment]
I'm not sure if @fivetanley has started work on this yet, I'll double check with him to see...

**Comment by fivetanley** [comment]
We do not intend to support sourcemaps for the globals build going forward.

**Comment by fivetanley** [comment]
We will likely need to make the sourcemap optional (detect if it is there) in the 2.3.0-betas npm modules if you are using bower.

**Comment by rwjblue** [comment]
Should be fixed by https://github.com/emberjs/data/pull/3944.

**Comment by rwjblue** [comment]
OK, the ember-data.js.map file is now present in canary branch and beta branch is being updated now. Closing this, but I'm happy to reopen if folks are still having issues.

**Comment by offirgolan** [comment]
That seemed to fix it. Thanks guys for the quick fix! :100:

**Comment by marcoow** [comment]
👍
