### ISSUE TITLE
Beta tag is empty

### ISSUE THREAD

**Issue by offirgolan** [components/ember-data#34]
components/ember-data#beta is empty

**Comment by bmac** [comment]
Thanks for reporting this. I'm not sure why that happened but I can look into it now.

**Comment by bmac** [comment]
Beta tag should be fixed now. https://github.com/components/ember-data/tree/beta. Looks like the issue was a missing module in the beta globals build script https://github.com/emberjs/data/commit/16ef6055875c025f8e630910ac9a3d85f89cb51c.

**Comment by offirgolan** [comment]
Thanks for the fix @bmac :smile_cat:
