### ISSUE TITLE
[Issue] Ember-Data 2.8.0 not tagged

### ISSUE THREAD

**Issue by piotrpalek** [components/ember-data#36]
This is a problem because services like https://cdnjs.cloudflare.com rely on the tags. So specifically because there is no 2.8.0 tag, there is no ember-data 2.8.0 on cdnjs, which in turn causes issues for [ember-twiddle](http://ember-twiddle.com) (can't use ember-data 2.8 because we use cdnjs to download ember and ember-data files)

**Comment by rwjblue** [comment]
Thanks for reporting!

@bmac / @fivetanley - Would one of y'all mind pushing the 2.8 build up and tagging?

**Comment by RobLoach** [comment]
https://github.com/components/ember-data/tree/2.8
